### ISSUE TITLE
上传文档并提问后报错，提示ValueError: "ChatResponse" object has no field "usage"

### ISSUE THREAD

**Issue by flickxie** [wzdavid/ThinkRAG#10]
提问后，可正常输出回复，然后报错如下：
```
2024-12-03 19:24:14.722 Uncaught app exception
Traceback (most recent call last):
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/root/ThinkRAG-main/app.py", line 48, in <module>
    pg.run()
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/navigation/page.py", line 303, in run
    exec(code, module.__dict__)
  File "/root/ThinkRAG-main/frontend/Document_QA.py", line 128, in <module>
    main()
  File "/root/ThinkRAG-main/frontend/Document_QA.py", line 118, in main
    chatbox()
  File "/root/ThinkRAG-main/frontend/Document_QA.py", line 71, in chatbox
    response_text = st.write_stream(response.response_gen)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/runtime/metrics_util.py", line 410, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/elements/write.py", line 174, in write_stream
    for chunk in stream:  # type: ignore
                 ^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/llama_index/core/llms/llm.py", line 127, in gen
    for response in chat_response_gen:
                    ^^^^^^^^^^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/llama_index/core/llms/callbacks.py", line 186, in wrapped_gen
    for x in f_return_val:
             ^^^^^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/llama_index/llms/ollama/base.py", line 335, in gen
    r["usage"] = token_counts
    ~^^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/ollama/_types.py", line 46, in __setitem__
    setattr(self, key, value)
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/pydantic/main.py", line 926, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "ChatResponse" object has no field "usage"
2024-12-03 19:24:14.955 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
```
猜测是输出统计信息时的报错？

**Comment by flickxie** [comment]
找到原因了，使用了更新版本的ollama，更改为0.3.3后不再报错
