### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.

### ISSUE THREAD

**Issue by xuyunlong123** [wzdavid/ThinkRAG#12]
Traceback (most recent call last):
  File "/data/anaconda3/envs/py391/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/data/anaconda3/envs/py391/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/data/big_model/app.py", line 10, in <module>
    from frontend.state import init_state
  File "/data/big_model/frontend/state.py", line 7, in <module>
    from server.index import IndexManager
  File "/data/big_model/server/index.py", line 8, in <module>
    from server.ingestion import AdvancedIngestionPipeline
  File "/data/big_model/server/ingestion.py", line 9, in <module>
    from server.stores.ingestion_cache import INGESTION_CACHE
  File "/data/big_model/server/stores/ingestion_cache.py", line 6, in <module>
    cache=RedisCache(redis_uri=REDIS_URI),
  File "/data/anaconda3/envs/py391/lib/python3.9/site-packages/llama_index/storage/kvstore/redis/base.py", line 65, in __init__
    self._async_redis_client = AsyncRedis.from_url(redis_uri, **kwargs)
  File "/data/anaconda3/envs/py391/lib/python3.9/site-packages/redis/asyncio/client.py", line 163, in from_url
    client = cls(
  File "/data/anaconda3/envs/py391/lib/python3.9/site-packages/redis/asyncio/client.py", line 341, in __init__
    self._single_conn_lock = asyncio.Lock()
  File "/data/anaconda3/envs/py391/lib/python3.9/asyncio/locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "/data/anaconda3/envs/py391/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.

**Comment by wzdavid** [comment]
谢谢反馈，是production模式用了redis吗？另外，可以试试python 3.12.0，之前没有在3.9上测试过

**Comment by xuyunlong123** [comment]
> 谢谢反馈，是production模式用了redis吗？另外，可以试试python 3.12.0，之前没有在3.9上测试过

还是开发模式，就是很奇怪，我要转成3.12看看么

**Comment by wzdavid** [comment]
可以试试3.12，是在3.12上开发和测试的。已经发现在旧版本python上运行，一些组件会有问题

**Comment by xuyunlong123** [comment]
感谢，我试下，然后反馈

**Comment by xuyunlong123** [comment]
> 可以试试3.12，是在3.12上开发和测试的。已经发现在旧版本python上运行，一些组件会有问题

安装环境的时候有报错，兼容性问题
![图片](https://github.com/user-attachments/assets/a7f3fb51-7d44-4f33-9755-bf86c8c7bf52)
