### ISSUE TITLE
上传文件后回答问题失败

### ISSUE THREAD

**Issue by tik-seven** [wzdavid/ThinkRAG#7]
我在本地部署成功后，使用ollama的llama3模型，配置成功。上传了一份docx文件成功，然后发送问题，后台报错：

`Traceback (most recent call last):
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\app.py", line 48, in <module>
    pg.run()
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\streamlit\navigation\page.py", line 303, in run
    exec(code, module.__dict__)
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\frontend\Document_QA.py", line 128, in <module>
    main()
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\frontend\Document_QA.py", line 118, in main
    chatbox()
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\frontend\Document_QA.py", line 71, in chatbox
    response_text = st.write_stream(response.response_gen)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\streamlit\runtime\metrics_util.py", line 410, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\streamlit\elements\write.py", line 174, in write_stream
    for chunk in stream:  # type: ignore
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\llama_index\core\llms\llm.py", line 127, in gen
    for response in chat_response_gen:
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\llama_index\core\llms\callbacks.py", line 186, in wrapped_gen
    for x in f_return_val:
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\llama_index\llms\ollama\base.py", line 333, in gen
    token_counts = self._get_response_token_counts(r)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduSyncdisk\wk\ThinkRAG-main\think\Lib\site-packages\llama_index\llms\ollama\base.py", line 198, in _get_response_token_counts
    total_tokens = prompt_tokens + completion_tokens
                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'`

**Comment by wzdavid** [comment]
感谢反馈，我们看一下

**Comment by tik-seven** [comment]
请问排查到原因了吗，需要提供更加详细的信息吗？

**Comment by wzdavid** [comment]
不好意思，还没有找到Windows系统重现该问题😅最近解决了一些bug，您可以用最新代码试试。也可以在Linux或Mac上使用
