### ISSUE TITLE
启动后打开web界面报错

### ISSUE THREAD

**Issue by flickxie** [wzdavid/ThinkRAG#9]
使用ollama，出现如下报错

```
2024-12-03 19:22:10.148 Uncaught app exception
Traceback (most recent call last):
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/root/ThinkRAG-main/app.py", line 24, in <module>
    init_state()
  File "/root/ThinkRAG-main/frontend/state.py", line 211, in init_state
    init_keys()
  File "/root/ThinkRAG-main/frontend/state.py", line 31, in init_keys
    ollama.get_model_list()
  File "/root/ThinkRAG-main/server/models/ollama.py", line 23, in get_model_list
    st.session_state.ollama_models.append(model["name"])
                                          ~~~~~^^^^^^^^
  File "/root/ThinkRAG-main/lib/python3.12/site-packages/ollama/_types.py", line 32, in __getitem__
    raise KeyError(key)
KeyError: 'name'
```

尝试进行如下修改后可以正常访问，获取到ollama模型清单(在241209拉取的最新版本中仍存在该问题)
```
(ThinkRAG-main) [root@ai models]# pwd
/root/ThinkRAG-main/server/models
(ThinkRAG-main) [root@ai models]# diff ollama.py ollama.py.bak
23,24c23
<             # xcq st.session_state.ollama_models.append(model["name"])
<             st.session_state.ollama_models.append(model["model"])
---
>             st.session_state.ollama_models.append(model["name"])

```

**Comment by flickxie** [comment]
找到原因了，使用了更新版本的ollama，更改为0.3.3后不再报错
